
default:
    @just --list

outdated:
    mint run swift-outdated

pre-commit:
    mkdir -p .git/hooks/pre-commit
    cp .scripts/pre-commit .git/hooks/pre-commit
    chmod +x .git/hooks/pre-commit

tools:
    mint bootstrap
    just pre-commit
