disabled_rules:
    - nesting
    - trailing_whitespace
    - trailing_comma
    - opening_brace
    - closure_parameter_position
    - function_body_length
    - inclusive_language
    - type_name
    - identifier_name
    - multiple_closures_with_trailing_closure
    - line_length
    - unused_setter_value
    - redundant_discardable_let
    - type_body_length
    - file_length
    - force_try
identifier_name:
    max_length: 60
    excluded:
        - i
        - at
        - id
        - me
        - e
        - ev
        - URL
        - h1
        - to
        - x
        - y
        - ok
        - by
excluded:
    - .git
opt_in_rules:
    - explicit_top_level_acl
    - modifier_order
    - sorted_imports
cyclomatic_complexity:
    ignores_case_statements: true
